src/Chat.tsx
=> Fix chatbot unmounting

README.md, src/Chat.tsx, src/Shell.tsx, src/Store.ts, src/scss/botchat.scss
/* Please update CHANGELOG.md. Under [Unreleased] section, describe your changes under 80 characters */
=> disable input feature

package-lock.json, package.json, src/Chat.tsx, webpack.config.js
/* Please update CHANGELOG.md. Under [Unreleased] section, describe your changes under 80 characters */
=> smartsupp handoff

src/Shell.tsx
feat: added autofocusing input after enabling text input
=> feat: FBOT-366 added autofocusing textarea

src/App.tsx
- Fixed carousel cards width in fullsized webchat.
=> fix: 🐛 fixed carousel width in fullsized webchat

samples/feedyou/modern.html, src/App.tsx
- Gave carousel cards fixed width
=> fix: 🐛 carousel cards fixed width

src/App.tsx
Bug-fix based on feedback from fincetrum, new webchat changes probably broken their WC, this PR solves the problem. Attachment to see what's the issue.
- fixed overflowing carousel card
- fixed showing arrow to scroll to the next item
=> fix: 🐛 overflowing carousel card

src/FormattedText.tsx
Made webchat to render XML as markdown.
=> fix: 🐛 rendering xml as markdown

src/App.tsx, src/AppService.tsx
- Added option to add partner logo to signature
=> feat: 🚀 added partner logo to signature

src/App.tsx
=> feat: 🚀 center signature in sidebar

src/App.tsx
- Fixed centring of full-size webchat template for IE11
=> fix: FBOT-742 fixed centering of full size template for IE

src/App.tsx, src/AppService.tsx
For GiGroup enabled adding customScript to config
=> feat: 🚀 enabled adding customScript to config

src/Chat.tsx, src/Store.ts
- moved typing indicator to state and made it customizable from props
=> feat: 🚀 moved typing delay to store

src/App.tsx, src/Store.ts
It was needed to use singleton in this case so I moved the logic to App.tsx
=> fix: 🐛 fixed delay using singleton

src/History.tsx
https://feedyou.atlassian.net/browse/FBOT-1363
=> fix: FBOT-1363 haprujici automaticky posun konverzace

src/FormattedText.tsx
/* Please update CHANGELOG.md. Under [Unreleased] section, describe your changes under 80 characters */
=> refactor : refactor markdown link composition

src/Chat.tsx
Trying to change DataLayer for google GTM
=> feat: dataLayerDRMAX

src/History.tsx
https://feedyou.atlassian.net/browse/FBOT-1363
=> fix: FBOT-1363 haprujici automaticky posun konverzace tollerance fix

src/App/templates/ExpandableTemplate/Signature/Signature.tsx
https://feedyou.atlassian.net/browse/FBOT-1676
=> fix: FBOT-1676  fix signature mode equals none

samples/feedyou/local.html, src/AdaptiveCardContainer.tsx, src/scss/botchat.scss
https://feedyou.atlassian.net/browse/FBOT-1671
=> fix: FBOT-1671 horni odsazeni nadpisu v carouselu

src/App/renderWebchatApp.tsx, src/App/templates/ExpandableTemplate/ExpandableTemplate.tsx, src/IntroMessage/PopupMessage.tsx, src/IntroMessage/utils.ts
https://feedyou.atlassian.net/browse/FBOT-1346
=> feat: FBOT-1346 upgrade the webchat knob with intro message further development

src/App/App.tsx
https://feedyou.atlassian.net/browse/FBOT-1755
=> fix: FBOT-1755 fix wc crashing when header prop is not provided

src/App/App.tsx, src/App/renderWebchatApp.tsx, src/App/templates/ExpandableTemplate/ExpandableTemplate.tsx, src/IntroMessage/PopupMessage.tsx, src/IntroMessage/utils.ts
https://feedyou.atlassian.net/browse/FBOT-1346
=> fix: FBOT-1346 upgrade the webchat knob with intro message further development

src/App/App.tsx, src/App/templates/ExpandableTemplate/Header.tsx
https://feedyou.atlassian.net/browse/FBOT-1750
=> fix: FBOT-1750 fix extrahtml

src/themes/FullScreenTheme.tsx
https://feedyou.atlassian.net/browse/FBOT-1768
=> fix: FBOT-1768 fulscreen odskoceny v mobilu

src/Chat.tsx
https://feedyou.atlassian.net/browse/FBOT-1455
=> chore: FBOT-1455 po stisku klavesy v try panelu se do konzole vypise chyba invariant violation

src/Chat.tsx
https://feedyou.atlassian.net/browse/FBOT-1636
=> fix: FBOT-1636  remove device detector

src/History.tsx, src/Store.ts, src/Strings.ts
Added alert on failed attachment upload
=> feat: alert when uploading attachment fails

src/Store.ts
Added type guard to fix ts error
=> fix: added type guard

src/Shell.tsx
Unfortunately there was still a bug in sending the query to the bot. Hopefully this the last autosuggest related PR ever
=> fix: FBOT-1001 normalizing already encoded uri part

src/themes/BaseTheme.tsx
Tak jsem to ještě učesal, aby to na mobilu vypadalo lépe ta tlačítka, zároveň ještě pár jiných drobnosti
=> fix: FBOT-2442 adaptive cards widths
